[project]
name = "senbot"
version = "2.3"
authors = [{name = "HITHELL"}]
requires-python = ">=3.13" 
description = "много функциональной Телеграм бот администратор"  
readme = "README.md"

[build-system]  
requires = ["setuptools", "setuptools-scm"]
