/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-119884-gfb65ecbc9b-20250613"
#endif /* AVUTIL_FFVERSION_H */
